# Generated by Django 4.2.11 on 2025-10-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='steps_taken',
            field=models.IntegerField(default=0),
        ),
    ]
